### ISSUE TITLE
Feature: WebHID

### ISSUE THREAD

**Issue by nytamin** [SuperFlyTV/xkeys#35]
I'm planning to work on adding support for WebHID, since it is now included in Chrome (as of version 89).
If anyone has any best-practices or ideas for how it's best implemented, I'm all ears.

My first problem to tackle: How should I go about with the Node-HID dependency, since that should be omitted in the web-version. 
@Julusian has solved it with the streamdeck by [publishing 2 separate npm-packages](https://github.com/Julusian/node-elgato-stream-deck#installing--usage). Perhaps that is the way to go?

**Comment by Julusian** [comment]
Yes, for the [streamdeck lib](https://github.com/julusian/node-elgato-stream-deck) I split it into 3 packages https://www.npmjs.com/org/elgato-stream-deck
* /core - houses pretty much all of the logic, anything that can be shared lives here. It defines an small hid abstraction interface to be implemented by the other modules https://github.com/Julusian/node-elgato-stream-deck/blob/master/packages/core/src/device.ts
* /node - the library intended for node use. This primarily does 2 things: implements that hid abstraction, and defines methods to list and open streamdecks. This is the package that depends on node-hid
* /webhid - very similar to the node one, but targets running in the browser.
* /webhid-demo - a demo site https://julusian.github.io/node-elgato-stream-deck/ used for testing the webhid implementation

The biggest downside to my approach that I have, is that all the api methods for writing to the device are promises. This is because they need to do that for webhid, but they will (for now) be synchronous in node.
Other than that, I am happy with what I have done. I just need to nudge users of the library across to the new package name :)
