### ISSUE TITLE
Backlight methods

### ISSUE THREAD

**Issue by cwilling** [SuperFlyTV/xkeys#49]
I see the api has various methods for setting backlights - including writing to the eeprom to make changes stick. Is there any way to retrieve the currently stored settings?

**Comment by nytamin** [comment]
We've only implemented methods for setting stuff at the moment. I don't know if it's possible to read the state of the backlights (@michaelhatPIengineering should know this).

Whats your use case for needing to read the states? (Myself, I always thought that setting all lights on startup would be enough.)

**Comment by cwilling** [comment]
Not a particularly compelling use case -  after playing around with the backlights, I might like to go back to initial settings without having to reboot/unplug the device.

BTW like unmounting/remounting disk drives, is there an equivalent for usb devices i.e. reconnecting without replugging them? If so, could that count as a reboot and restore burnt in settings?

**Comment by michaelhatPIengineering** [comment]
The very newest X-keys do have a way get the back light state. but most do not.
Our new rule is if there is a set command there should be a get also. But that has not always been the case. 

For all X-keys there is a reboot command. It essentially causes the X-keys to shut down and then the OS will re-discover the device. 

Send an output report of 238 to any X-keys and it will reboot. 

I hope to get back to adding some more output functions now that I have a node RED node (thanks Chris) I can play on my PI so that should inspire me to get back to work here

Michael

**Comment by cwilling** [comment]
Further to soft reboot idea, I see there's a 0,238,0... write command available (Report 21 - described as "Reboot Device" in the data reports from PIEng). I wonder if that would work?

Ah - Michael beat me to it while I was writing ...

**Comment by cwilling** [comment]
PR #50 adds rebootDevice()

**Comment by cwilling** [comment]
Thanks for the merge. Since only the very newest devices can read state of backlights, rebooting a device is a pretty good solution.
